Resources:
  xMyRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      Name: "my-req-validator"
      RestApiId:
        Ref: ApiGatewayRestApi
      ValidateRequestBody: true
      ValidateRequestParameters: false
